apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: annotations-spinapp
spec:
  image: "ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0"
  replicas: 1
  executor: containerd-shim-spin
  serviceAnnotations:
    key: value
  deploymentAnnotations:
    key: value
    multiple-keys: are-supported
  podAnnotations:
    key: value
