apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: resource-requirements-spinapp
spec:
  image: "ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0"
  replicas: 1
  executor: containerd-shim-spin
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 400Mi
