apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: runtime-config
spec:
  image: "ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0"
  replicas: 1
  executor: containerd-shim-spin
  runtimeConfig:
    sqliteDatabase:
      - name: "default"
        type: "libsql"
        options:
          - key: "url"
            value: "https://sensational-penguin-ahacker.libsql.example.com"
          - key: "token"
            valueFrom:
              secretKeyRef:
                name: "my-super-secret"
                key: "turso-token"

    llmCompute:
      type: "remote_http"
      options:
        - key: "url"
          value: "https://llm-app.fermyon.app"
        - key: "token"
          valueFrom:
            secretKeyRef:
              name: "my-super-secret"
              key: "llm-token"

    keyValueStores:
      - name: "default"
        type: "redis"
        options:
          - key: "url"
            valueFrom:
              secretKeyRef:
                name: "my-super-secret"
                key: "redis-full-url"

